# Generated by Django 3.0.8 on 2020-08-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigbang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigbangtheory',
            name='performance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
